### PR TITLE
Fixing the instantiate bug

### PR DESCRIPTION
**Pull request by icodeforyou**
Please merge so that we can use npm to install this plugin and its updated dependencies...

### CODE REVIEW

**Comment by rrees** [comment]
@hmgibson23

**Comment by rrees** [comment]
@icodeforyou Can you say why you want to merge this? We believe html-janitor v0.3.0 was primarily to include a Bower-compatible build. I'm not sure there is any function change in what you're proposing.

**Comment by icodeforyou** [comment]
@rrees I didnt check if there was any changes between the versions, but the plugin didnt work for us until I found the solution thats in this PR. Choosing the newer and updated version of html-janitor seemed to be a good choice seeing that the bower.json contained the newer version `0.3.0`.  Sorry for my lazyness :)

I have reverted back `package.json`. But the other change should be merged.

**Comment by rrees** [comment]
@icodeforyou I'm not sure this is correct either, HTMLJanitor is meant to constructed directly, if you look at the code not via a factory method (which I suspect has been added by the loader)

**Comment by rrees** [comment]
@icodeforyou I will be publishing a updated NPM version as per the issues on HTML Janitor though

**Comment by icodeforyou** [comment]
@rrees we encounter this problem when constructing HTMLJanitor directly.
[http://take.ms/93t4u](http://take.ms/93t4u)

And we use the plugin in a React component like this:
````javascript
scribe.use(ScribePluginSanitizer({
            tags: {
                p: {},
                b: {},
                strong: {},
                i: {},
                em: {},
                strike: {},
                del: {},
                sub: {},
                sup: {},
                br: {},
                a: { href: true, mailto: true , class: true},
                blockquote: {},
                img: { src: true },
                'div': { contenteditable: true },
                span: { class: true },
                ul: { contenteditable: true, id: true, class: true },
                li: { class: true },
                small: {}
            }
        }));
````

**Comment by rrees** [comment]
@icodeforyou I have released an updated html-janitor which should fix your NPM install issue.

However on the constructor issue, your change would break our code. Please see the Scribe examples (in the source and on the [Github Pages](https://guardian.github.io/scribe)) to see how this is used.

Therefore I can't merge this change.

**Comment by icodeforyou** [comment]
@rrees Thanks for updating the html-janitor package.json, but, shouldnt this plugins package.json also be updated to use the 0.3.* version of html-janitor? When I run npm install/update on the plugin it only downloads the 0.2.0 version.

And also, is there a way to fix the problem we are having with this plugin:
`Uncaught TypeError: object is not a function`

````javascript
var HTMLJanitor = require('html-janitor'), merge = require('lodash-amd/modern/objects/merge'), cloneDeep = require('lodash-amd/modern/objects/cloneDeep');
'use strict';
module.exports = function (config) {
    var configAllowMarkers = merge(cloneDeep(config), { tags: { em: { 'class': 'scribe-marker' } } });
    return function (scribe) {
        var janitor = new HTMLJanitor(configAllowMarkers);
        scribe.registerHTMLFormatter('sanitize', janitor.clean.bind(janitor));
    };
};
````

**Comment by rrees** [comment]
I think is due to the way you are loading the components, currently we only really use Scribe ourselves via Bower, if you are using something like Browserify then there might be an issue with the loading scheme.

Look at the [Scribe example page](http://guardian.github.io/scribe/) to see how we are loading the plugin.

**Pull request closed without merging**
